version: '3.6'

services:
  api:
    image: quay.io/go-skynet/local-ai:v1.25.0-ffmpeg
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./models:/models:cached
      - ./generated/images:/tmp/generated/images/
    command: ["/usr/bin/local-ai" ]
